//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeoSoftTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNeoData
    {
        public int Row_Id { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PanNumebr { get; set; }
        public string PassportNumber { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public string ProfileImage { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblState tblState { get; set; }
    }
}
